server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: 4KaGKf_lCheBJgFq6kRR2bomch50pa-AwILPI0GA
  secretKey: dnNuY9iRLRYP34RSRFXUj1urlsKiWIPpISbx7Mhg
  bucket: mingren-blog-1